### ISSUE TITLE
Project Tracker

### ISSUE THREAD

**Issue by Jashcraf** [Jashcraf/keck-polarization#3]
## Project Phases
- [x] Construct Polarimetric Model of the ORKID Imaging Path
- [x] Assess Jones Pupils v.s. Wavelength
- [ ] Assess Jones Pupils v.s. FoV
- [ ] Assess Polarization Aberrations v.s. Optical Element
- [ ] Determine FoV requirements for polarimetry mode (motivate by largest interesting disk, maximize by 1/2 of FoV)
- [ ] Select polarization beam splitting prism that satisfies the FoV requirements above
- [ ] #11
- [x] Physical optics simulation of ORKID polarimeter using <insert diffraction tool here>
